import com.example.rule.model.Participant;
global com.example.rule.model.Rate rate;

dialect "mvel"


rule "Checking Credit Score less than 550"
 when
  Participant(creditScore < 550 , annualSalary > 50000,  loanAmount < (2 * existingDebt))
 then
  rate.setLoanStatus("Rejected");
  rate.setLoanRate(999);
end
rule "Checking Credit Score less than 650"
 when
  Participant((creditScore < 650 && creditScore >= 550), annualSalary > 50000,  loanAmount < (2 * existingDebt))
 then
  rate.setLoanStatus("Approved");
  rate.setLoanRate(7.25);
end

rule "Checking Credit Score less than 750"
 when
  Participant((creditScore < 750 && creditScore >= 650), annualSalary > 50000,  loanAmount < (2 * existingDebt))
 then
  rate.setLoanStatus("Approved");
  rate.setLoanRate(6.25);
end
 rule "Checking Credit Score greater than 750"
 when
   Participant(creditScore >= 750, annualSalary > 50000,  loanAmount < (2 * existingDebt))
 then
   rate.setLoanStatus("Approved");
   rate.setLoanRate(5.25);
 end