package com.example.rules

import com.example.rule.model.CartItem;
global com.example.rule.model.Rate rate;
import com.example.rule.model.Promotion;
import com.example.rule.model.Product;


//
//rule "Apply Promotion 1"
//    when
//
//        $cartItem : CartItem( totalPrice > 0)
//        $product : Product() from $cartItem.products
//        $promotion: Promotion(productId == null)
//    then
//        System.out.println($promotion.getType());
//        // Áp dụng khuyến mãi vào giỏ hàng
//        rate.addPromotion($promotion);
//
//end

rule "Apply Promotion"
    when

        $cartItem : CartItem($cartItem.getTotalPrice() > 0)
        $product : Product()
        $promotion: Promotion(productId == $product.getId() || productId == null)
    then
        // Áp dụng khuyến mãi vào giỏ hàng
        rate.addPromotion($promotion);

end
